### ISSUE TITLE
Pull Items to Inventory option no longer working and missing from config

### ISSUE THREAD

**Issue by OceanSnipe17** [AzumattDev/CraftyBoxes#2]
The Pull Items to Inventory option that is displayed on the mod page does not work (default LeftControl key) and it is missing from the default config that's created for the mod.

https://valheim.thunderstore.io/package/Azumatt/AzuCraftyBoxes/
![image](https://github.com/AzumattDev/CraftyBoxes/assets/46897556/856aa35e-eba7-4ef2-8fa3-14a75b94b1a9)

Even adding "PullItemsKey = LeftControl" in the Azumat.AzuCraftyBoxes.cfg config does not alter this missing functionality.

**Comment by AzumattDev** [comment]
That's a mix up for leaving it there, but it's listed in the changelogs for the mod that it was removed.

**Comment by OceanSnipe17** [comment]
Apologies for the late response. Is there a chance this will be either added back into this mod at some point or perhaps made into a separate mod?

**Comment by AzumattDev** [comment]
> Apologies for the late response. Is there a chance this will be either added back into this mod at some point or perhaps made into a separate mod?

In the changelog I answer this question.

![image](https://github.com/AzumattDev/CraftyBoxes/assets/80414405/f1c86d61-78f4-4ce8-8cd0-0bfdea5379d1)

**Comment by OceanSnipe17** [comment]
Ah, if I would just read I would have saved you the time. My sincerest apologies.
